### ISSUE TITLE
[Issues/Requests] Library moved to another drive and HappyPanda can't build it again.

### ISSUE THREAD

**Issue by HASJ** [Pewpews/happypanda#35] opened 2015-10-30 22:33 UTC
I'm on Windows 10.
I bought a new HD because space was becoming an issue and moved my collection there.
Opened HappyPanda v0.24 and all thumbnails were blank spaces. Okay, expected. Still weird because I also expected HP to erase them, since their files weren't located. [Becomes another issue]

[Request 1] Can't clear the library in a single move.

[Issue 1] Selected all blank mangas (1130 items) whose files weren't not even there and deleted them from the HP library, still took a stupid amount of time all the while using heaps of processing power, locking HP down whenever its window was open and focused.

Remove the original folder from the monitoring and add-in the new location. Restart HP. Ok.

[Issue 2] HP does its initial scan. Nothing is detected.

[Issue 3] Only way to add new files to the library is by manually adding them. Monitoring folders does nothing at all.

At this point I think my HP got corrupted or something. Get v0.25.

Everything is still the same.

[Issue 4] As a test, download a gallery from Ex to see if it gets automatically added to the library. Nope.

[Request 2] Option to queue gallery downloads so you can paste some links broken by lines. I could handle 8 simultaneous downloads without a single problem, the only annoyance was having to go between HP and Firefox to copy a new gallery link and add them to HP and again and again.

[Issue 5] Twice during while changing windows and adding links to download, HP crashed. The only things I was doing was Alt+Tabbing, CTRL+C/V, Enter and the mouse, in a really quick fashion. Could not reproduce on demand. The partial .part files in "HP/downloads" were fine and able to be resumed/
be overwritten normally.

I think that's it. Oh yeah.

[Request 3] Categories within the manager, make an item be able to belong to multiple categories and be able to move physically move items on a category to a folder within its current place (optional).
Example: "Western Cosplay Collection" belongs to the Cosplay and the Western Cosplay categories, when moving a selection of items who also contain Cosplay Collection, show a prompt to select which folder Western Cosplay Collection with be physically moved to.

Hope I'm not being a dick requesting all that stuff but I genuinely think they're necessary to the program (bias much? :D)

EDIT: [Request 4] Add a check to see if a gallery has already been added to the list or already exists in the /downloads folder and if you want to overwrite it (possibly showing size/date/number of files in the gallery comparisons).

**Comment by twiddli** [comment] 2015-10-31 00:04
> Opened HappyPanda v0.24 and all thumbnails were blank spaces. Okay, expected. Still weird because I also expected HP to erase them, since their files weren't located.

Sometime in the future, I'll make it handle moving locations more gracefully. It'll be something along the lines of checking each gallery location if they still exists... and then notify the user about those that don't exist anymore and what should be done to them. Thanks for reminding me.

> [Request 1] Can't clear the library in a single move.

You're right, there's no quick way of deleting your library from within the program. To delete your whole library, you just delete the **db** folder. I'll add a button that'll do this for you in the settings, I think.

> [Issue 1] Selected all blank mangas (1130 items) whose files weren't not even there and deleted them from the HP library, still took a stupid amount of time all the while using heaps of processing power, locking HP down whenever its window was open and focused.

The process of deleting gallery isn't being handled gracefully, yet. I think, generally, HP will lock up when deleting more than 50 galleries. I'll add it to my to-do list. Thanks for the report.

> Remove the original folder from the monitoring and add-in the new location. Restart HP. Ok.
> [Issue 3] HP does its initial scan. Nothing is detected.

I need you to provide me all your logs to find the cause of this. In the happypanda folder, logs named `happypanda.log` and/or `happypanda.log.x` where `x` is a number, should be there.

> [Issue 4] Only way to add new files to the library is by manually adding them. Monitoring folders does nothing at all.

Logs please~

> [Issue 5] As a test, download a gallery from Ex to see if it gets automatically added to the library. Nope.

This issue has already been fixed in the upcoming new version! (_v0.26_)

> [Request 2] Option to queue gallery downloads so you can paste some links broken by lines. I could handle 8 simultaneous downloads without a single problem, the only annoyance was having to go between HP and Firefox to copy a new gallery link and add them to HP and again and again.

The downloader is in very much alpha state (just like the program, haha) so suggestions like these are very much welcome. I realize alt-tabbing between windows is very tedious so I'll implement some features that'll help much in that regard. Something like, auto download when pasting link, auto paste for you when it detects a link in the clipboard (if feasible), and maybe import links from a text file or something. Things are gonna be so good!

> [Issue 6] Twice during while changing windows and adding links to download, HP crashed. The only things I was doing was Alt+Tabbing, CTRL+C/V, Enter and the mouse, in a really quick fashion. Could not reproduce on demand. The partial .part files in "HP/downloads" were fine and able to be resumed/
> be overwritten normally.

Hmmm.. I've got a bad feeling about this issue. Hopefully your logs can help. Crashes are generally hard to fix if not reproduce-able (and even then, still hard to fix).

> [Request 3] Categories within the manager, make an item be able to belong to multiple categories and be able to move physically move items on a category to a folder within its current place (optional).
> Example: "Western Cosplay Collection" belongs to the Cosplay and the Western Cosplay categories, when moving a selection of items who also contain Cosplay Collection, show a prompt to select which folder Western Cosplay Collection with be physically moved to.

Moving gallery files/folders and automatically organizing them (think iTunes) is something in the plannings, though very far in the future.. About having a gallery be in multiple categories isn't something I have ever thought of. If you can create a new issue about this request then I might implement it when implementing the gallery organizing.

> [Request 4] Add a check to see if a gallery has already been added to the list or already exists in the /downloads folder and if you want to overwrite it (possibly showing size/date/number of files in the gallery comparisons).

Sounds reasonable. I'll do something about it.

Many thanks for the suggestions and issue reporting. Now I just need your logs so I can try and identify some of those issues you've been experiencing.

**Comment by HASJ** [comment] 2015-10-31 04:43
https://drive.google.com/file/d/0BwLhfN-Yum0hY24tT2NGNmJ6ZUU/view?usp=sharing < log

The log does not go further back because as I suspected v0.24 was broken, I deleted its folder but I do think that the downloader crashes happened with v0.25. Downloading starts at line 3950.

After checking the log, I discovered that indeed HP was monitoring the files, it was just going to finish ALL of them before giving me input on it. Adding a simple icon/text that HP has detected new files in the folder and is parsing them, I think this resolves issues 2 to 5. Issue 5 I think it means that HP will finish checking everything and THEN add the downloaded galleries.

This is only a portion of my collection, containing 513 items. On line 14730 I had just deleted the DB folder. One and a half hour later (more give than take), HP is currently at 52% "Searching for galleries...". There is more than 1500 items on this HD so can you really blame me for thinking HP was doing nothing? He was just going to need almost all day long to parse the whole thing.

Also noticed that HP creates each files thumbnails after it parses all files. I think you could make it show the thumbs right after it goes through a file, akin to ComicRack. This would completely erase the feeling that HP is doing nothing when, in fact, it is monitoring the folder and working normally.

EDIT: After finishing the "Searching for galleries...", HP is populating the database with only 225 galleries. Uh?
EDIT2: Regarding the 225 galleries, it is happening because I'm using folders to separate artists with more than one manga and HP is putting those folders together and thinking those are separate chapters of a series.

While adding about 50 files, HP did a very strange hang that froze the window and it was not responding to anything. First time it happened, again, I thought it had crashed. Second time, checked the logs and it was still processing the files. I think it happened on line 20230.

**Comment by twiddli** [comment] 2015-10-31 12:42
Thanks for the log! While investigating, I did indeed find some errors/bugs!

> Issue 5 I think it means that HP will finish checking everything and THEN add the downloaded galleries.

This is not the case. The fault was in the code, which is what I'm going to fix. 

> Also noticed that HP creates each files thumbnails after it parses all files. I think you could make it show the thumbs right after it goes through a file, akin to ComicRack. This would completely erase the feeling that HP is doing nothing when, in fact, it is monitoring the folder and working normally.

Will be commented on here #38 

It's gonna take a while looking through the log. Thanks for the detailed reports!

**Comment by twiddli** [comment] 2016-01-06 21:33
Closing this thread since all issues and requests seems to have been fixed or made into separate github issues!

**Closed as completed by twiddli** 2016-01-06 21:33 UTC
Labels: bug, enhancement, feature suggestion
