### ISSUE TITLE
Still crashing while getting metadata

### ISSUE THREAD

**Issue by JacobDNN** [Pewpews/happypanda#144] opened 2016-03-11 18:31 UTC
Hi. It seems that [previous](https://github.com/Pewpews/happypanda/issues/126) fix doesn't help. Happypanda still crashes if select "Get metadata for all galleries". 

[debug.txt](https://github.com/Pewpews/happypanda/files/169737/debug.txt)

**Comment by twiddli** [comment] 2016-03-11 20:17
Is it always failing at the same gallery?
If yes, are you able to fetch metadata for it individually by right-clicking and click `get metadata`?
And also, can you send me the faulty gallery then?

If no, and since I'm not able to reproduce the issue, could you help me debug by heading over to the gitter chat whenever you have time? I'll just be asking you to run a custom-build and then post results, if that's okay with you.

**Comment by JacobDNN** [comment] 2016-03-12 04:52
I can go to gitter chat, no problem.

It fails on random gallery if i try to get metadata for more than one. If i select a few galleries and press "Get metadata for selected" it also fails. Usually this happens after processing 2-3 galleries, but sometimes it can process more.

I can get metadata for them individually, it works good.

Here's two tests. In the first, i selected around 10 galleries and try to get metadata. It fails in batch fetching, but succeeded in individually. In the second test i selected another 18 galleries and try to get metadata for them a few times, it all failed. Individual fetching works fine, except two galleries wasn't found.

[debug.zip](https://github.com/Pewpews/happypanda/files/170265/debug.zip)

**Comment by Indy27** [comment] 2016-03-16 02:26
Yeah, I just downloaded the latest version and tried batch fetching, same problem.

**Comment by twiddli** [comment] 2016-03-18 22:51
> latest version

You mean v0.28.1?

The issue OP was experiencing has been fixed and will be in v0.29. 
If you're on 64bit Windows, you can download the [latest debug build](https://github.com/Pewpews/happypanda/releases/tag/v0.28.2-DEBUG) which has the fix.

**Closed as completed** 2016-03-25 14:56 UTC
Labels: bug
